// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarehouseApi.Infrastructure.Data;

#nullable disable

namespace WarehouseApi.Infrastructure.Migrations
{
    [DbContext(typeof(Contex))]
    [Migration("20251015182915_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WarehouseApi.Core.Entities.Categorias", b =>
                {
                    b.Property<int>("CategoriasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriasId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriasId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriasId = 1,
                            Nombre = "Electronicos"
                        },
                        new
                        {
                            CategoriasId = 2,
                            Nombre = "Ropa"
                        },
                        new
                        {
                            CategoriasId = 3,
                            Nombre = "Hogar"
                        },
                        new
                        {
                            CategoriasId = 4,
                            Nombre = "Juguetes"
                        },
                        new
                        {
                            CategoriasId = 5,
                            Nombre = "Deportes"
                        },
                        new
                        {
                            CategoriasId = 6,
                            Nombre = "Libros"
                        },
                        new
                        {
                            CategoriasId = 7,
                            Nombre = "Belleza"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
